language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools
     - extra

    # The SDK version used to compile your project
    - android-15

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-15
    # - sys-img-x86-android-17


  env:
    matrix:
      - ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a

  # Emulator Management: Create, Start and Wait
  before_script:
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

  script:
    - ./gradlew check -PdisablePreDex --continue --stacktrace
    - adb devices
    - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

  # found this at http://panavtec.me/continous-integration-on-android-with-travis-ci/
  after_failure:
    - wget http://imgur.com/tools/imgurbash.sh
    - chmod a+x imgurbash.sh
    - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
    - ./imgurbash.sh screen.png
    - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
